version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    networks:
      - test_network
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - test_network
  e2e:
    build: ./e2e
    depends_on:
      - web
    environment:
      - CYPRESS_baseUrl=http://web:3000
    command: npx cypress run
    volumes:
      - ./e2e:/app
    networks:
      - test_network

networks:
  test_network: